### ISSUE TITLE
Tiamat mod issue for c041_01-bugs_bunnay-swap

### ISSUE THREAD

**Issue by damnjp** [LokiCoder/destiny-child-tools#24]
The center of the image is always at her lower body

Leave this Mod ID here: c041_01-bugs_bunnay-swap

Leave this link here: http://localhost:3000/destiny-child-tools/childs/c041/

**Comment by LokiCoder** [comment]
This should have been fixed when installing from the app with automatic application of model_info.json adjustments for swaps.
