### ISSUE TITLE
Morrigan mod issue for c039_00

### ISSUE THREAD

**Issue by verysadhelp** [LokiCoder/destiny-child-tools#29]
Recently used previous version, I was able to instal mods for Mona, Tiamat, Maat, Sytry and Chang'e but I was unable to use the pactmaker skin for Morrigan nor a skin for Inanna. Today I updated to the  newest version, tried to instal the pactmaker skin for Morrigan and after restarting all character models were messed up, showing only the silouette of Syrinx out of frame.
![Screenshot_20191122-001048_Destiny Child](https://user-images.githubusercontent.com/58063722/69402156-9a47c080-0cbc-11ea-91be-1c008b65e580.jpg)

Leave this Mod ID here: c039_00

Leave this link here: https://lokicoder.github.io/destiny-child-tools/childs/c039/

**Comment by LokiCoder** [comment]
This should be fixed with latest app releases.
