### ISSUE TITLE
Version 0.0.7, Installing a mod removes all characters.

### ISSUE THREAD

**Issue by TheWeezel** [LokiCoder/destiny-child-tools#30]
Upon updating to v0.0.7 I attempted to install a mod for Mammon with the game closed.  Upon opening the game I found any character I opened to look at appeared to be a static silhouette of Syrinx.  Restoring the Globald Model_Info.Json seems to reset the visuals back.  I have also tried with Neith and had the same result.  I also tested with changing the Human Calypso (C038_0) that is the current splash screen character, this resulted in the change being shown however when entering the game the same silhouette appeared.  Doing a restore of just Human Calypso did not fix all the issues and required a full restore also.

**Comment by LokiCoder** [comment]
This should be fixed in latest releases. Sorry about that!
