### ISSUE TITLE
New mod for Master

### ISSUE THREAD

**Issue by Vincentlee0050** [LokiCoder/destiny-child-tools#31]
[What is the name of the modder?]

[What is the name of the mod? (a word or two)]

[Include a link to the downloadable UNIVERSAL or KR/JP formatted PCK file for your mod. PCK files formatted exclusively for Global are not supported.]

Leave this link here: http://localhost:3000/destiny-child-tools/childs/c000/

**Comment by LokiCoder** [comment]
No PCK download link provided
