### ISSUE TITLE
Missing Childs

### ISSUE THREAD

**Issue by MookaShakaPaka** [LokiCoder/destiny-child-tools#35]
Anyway to fix invisible childs like Leda and Freesia? Don't want to dl it and reset it if I don't like the change so I have to redownload every other child.

**Comment by LokiCoder** [comment]
You _should_ be able to re-download the original PCKs to fix this. https://github.com/LokiCoder/destiny-child-tools/releases/tag/v0.0.12 has a fix for a related crash inntroduced in `v0.0.11`. Let me know how it goes.

**Comment by MookaShakaPaka** [comment]
Oh I meant how both girls can't be seen in dc mods app.

**Comment by LokiCoder** [comment]
Unfortunately there are issues when decryption their PCK files where a `.mmd` file is found in place of the usual Live2D data with accompanying model JSON file. No one has figured out how to decrypt these yet.
