### ISSUE TITLE
New mod for Guardian Chang'e

### ISSUE THREAD

**Issue by gs828** [LokiCoder/destiny-child-tools#37]
[What is the name of the modder?]

[What is the name of the mod? (a word or two)]

[Include a link to the downloadable UNIVERSAL or KR/JP formatted PCK file for your mod. PCK files formatted exclusively for Global are not supported.]

Leave this link here: http://localhost:3000/destiny-child-tools/childs/c355/

**Comment by LokiCoder** [comment]
You forgot to give me a link to download the PCK.
