### ISSUE TITLE
New mod for ?

### ISSUE THREAD

**Issue by chanks-beep** [LokiCoder/destiny-child-tools#7]
[What is the name of the modder?]

[What is the name of the mod? (a word or two)]

[Include a link to the downloadable UNIVERSAL or KR/JP formatted PCK file for your mod. PCK files formatted exclusively for Global are not supported.]

Leave this link here: http://localhost:3000/destiny-child-tools/childs/sc421/

**Comment by LokiCoder** [comment]
Not filled out. Closing.
